/*  list item type
    menuName(breakfast & snacks) => type[lite]
    menuName(startter) => type[starter]
    menuName(soup) => type[soup]
    menuName(pizza) => type[pizza]
    menuName(lunch & dinner) => type[startter+soup+pizza+meal]
    menuName(dessert) => type[dessert]
    menuName(drink) => type[drink]
    menuName(pureveg) => category(veg)
*/
const Food=[
    {
        id: 1,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"3-in-1.jpg",
        category:"veg",
        type:"dessert",
        name:"3 in 1 icecream",
        rate:"150",
        des:"cherry on the top 😍",
        tag1:"strawberry",
        tag2:"vanilla"
    },
    {
        id: 2,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"3-choco.jpg",
        category:"non-veg",
        type:"dessert",
        name:"3-choco",
        rate:"150",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },
    {
        id: 3,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"azmiri-fish.jpg",
        category:"non-veg",
        type:"meal",
        name:"azmiri fish",
        rate:"180",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },
    {
        id: 4,
        fnc: function print(arg){ return(arg)},
        offer:"10",
        img:"berries-kiwie.jpg",
        category:"veg",
        type:"dessert",
        name:"berries kiwie",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },
    {
        id: 5,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"beyti-kabab.jpg",
        category:"non-veg",
        type:"meal",
        name:"beyti kabab",
        rate:"120",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 6,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"burgar.jpg",
        category:"non-veg",
        type:"lite",
        name:"burger",
        rate:"100",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 7,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"burrah-kabab.jpg",
        category:"non-veg",
        type:"starter",
        name:"burrah kabab",
        rate:"180",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 8,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"butter-masala.jpg",
        category:"non-veg",
        type:"meal",
        name:"butter chicken",
        rate:"165",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 9,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"butter-panner.jpg",
        category:"veg",
        type:"meal",
        name:"butter panner",
        rate:"220",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },
    {
        id: 10,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"butter-roti.jpg",
        category:"veg",
        type:"meal",
        name:"butter roti",
        rate:"30",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 11,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"potato-soup.jpg",
        category:"non-veg",
        type:"soup",
        name:"Bread soup",
        rate:"120",
        des:"light and healthy.",
        tag1:"Stew",
        tag2:"paper"
    },
    {
        id: 12,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"bananas.jpg",
        category:"veg",
        type:"lite",
        name:"Banana",
        rate:"40",
        des:"fresh fruit with chocolate garnish",
        tag1:"chocolate",
        tag2:"sugar"
    },
    {
        id: 13,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"beef-stake.jpg",
        category:"non-veg",
        type:"starter",
        name:"beef stake",
        rate:"200",
        des:"hot and spicy",
        tag1:"stake",
        tag2:"juicy"
    },
    {
        id: 14,
        fnc: function print(arg){ return(arg)},
        offer:"10",
        img:"champagne.jpg",
        category:"veg",
        type:"drink",
        name:"champagne",
        rate:"1600",
        des:"I don't know what to write here 😏",
        tag1:"smooth",
        tag2:"royal"
    },
    {
        id: 15,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"coca-burst.jpg",
        category:"",
        type:"dessert",
        name:"coca burst",
        rate:"80",
        des:"sweet sugary and creamy",
        tag1:"creemy",
        tag2:"moose"
    },
    {
        id: 16,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"cofee.jpg",
        category:"",
        type:"drink",
        name:"coffee",
        rate:"50",
        des:"its hot",
        tag1:"hot",
        tag2:"southIndian"
    },
    {
        id: 17,
        fnc: function print(arg){ return(arg)},
        offer:"10",
        img:"italian-cuisine-pizza.jpg",
        category:"",
        type:"pizza",
        name:"cuisine pizza",
        rate:"550",
        des:"prawn and mushrooms",
        tag1:"signature👌",
        tag2:"thai"
    },
    {
        id: 18,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"cornflex.jpg",
        category:"",
        type:"lite",
        name:"cornflakes",
        rate:"75",
        des:"healthy breakfast",
        tag1:"breakfast",
        tag2:"milk"
    },
    {
        id: 19,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"cupcake.jpg",
        category:"",
        type:"dessert",
        name:"cupcake",
        rate:"80",
        des:"muffins with cream",
        tag1:"cream",
        tag2:"kids"
    },
    {
        id: 20,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"capachino.jpg",
        category:"veg",
        name:"cappuccino",
        type:"drink",
        rate:"150",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 21,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"chicken-biriyani.jpg",
        category:"non-veg",
        type:"meal",
        name:"chicken biriyani",
        rate:"220",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 22,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"chicken-breast.jpg",
        category:"non-veg",
        type:"starter",
        name:"chicken star",
        rate:"250",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },
    {
        id: 24,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"chicken-stew.jpg",
        category:"non-veg",
        type:"soup",
        name:"chicken stew",
        rate:"150",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 25,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"chicken-wings.jpg",
        category:"non-veg",
        type:"starter",
        name:"chicken wings",
        rate:"250",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 26,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"choco-holifield.jpg",
        category:"non-veg",
        type:"dessert",
        name:"choco holifield",
        rate:"800",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"premium",
    },
    {
        id: 27,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"chocolate-moose.jpg",
        category:"non-veg",
        type:"dessert",
        name:"chocolate moose",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 28,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"coco-rose.jpg",
        category:"non-veg",
        type:"dessert",
        name:"coco rose",
        rate:"180",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 29,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"coco-star.jpg",
        category:"non-veg",
        type:"dessert",
        name:"coco nest",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 23,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"chicken-drum-stick.jpg",
        category:"non-veg",
        type:"starter",
        name:"drum stick",
        rate:"250",
        des:"Group adda starter.",
        tag1:"crunch",
        tag2:"American"
    },
    {
        id: 30,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"dal-chawal.jpg",
        category:"veg",
        type:"meal",
        name:"dal chawal",
        rate:"100",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 31,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"dhosa.jpg",
        category:"veg",
        type:"meal",
        name:"dhosa",
        rate:"150",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 32,
        fnc: function print(arg){ return(arg)},
        offer:"20",
        img:"dry-fruit-cake.jpg",
        category:"non-veg",
        type:"dessert",
        name:"dry fruit cake",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 33,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"de-latte.jpg",
        category:"non-veg",
        type:"dessert",
        name:"de latte",
        rate:"225",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 34,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"ella-oslon.jpg",
        category:"veg",
        type:"dessert",
        name:"ella oslon",
        rate:"115",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },
    {
        id: 35,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"fish-curry.jpg",
        category:"non-veg",
        type:"meal",
        name:"fish curry",
        rate:"175",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 36,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"fish-finger.jpg",
        category:"non-veg",
        type:"starter",
        name:"fish nuggets",
        rate:"120",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 37,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"fried-momo.jpg",
        category:"non-veg",
        type:"starter",
        name:"fried momo",
        rate:"165",
        des:"I don't know what to write here 😏",
        tag1:"chicken",
        tag2:"tag2",
    },
    {
        id: 38,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"french-fries.jpg",
        category:"",
        type:"lite",
        name:"french fries",
        rate:"70",
        des:"deep fried potato with ketchup",
        tag1:"kfc",
        tag2:"ketchup"
    },
    {
        id: 39,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"gulab-jamun.jpg",
        category:"veg",
        type:"dessert",
        name:"gulabjamun",
        rate:"60",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 40,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"honey-lemon.jpg",
        category:"veg",
        type:"drink",
        name:"honey lemon",
        rate:"100",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 41,
        fnc: function print(arg){ return(arg)},
        offer:"10",
        img:"chicken-hari.jpg",
        category:"non-veg",
        type:"starter",
        name:"hariali korma",
        rate:"250",
        des:"punjab on plate",
        tag1:"chicken",
        tag2:"desi"
    },
    {
        id: 42,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"chicken-leg.jpg",
        category:"non-veg",
        type:"starter",
        name:"hot wings",
        rate:"250",
        des:"fried and juicy",
        tag1:"chicken",
        tag2:"fried"
    },
    {
        id: 43,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"half-boiled-tost.jpg",
        category:"non-veg",
        type:"lite",
        name:"half boil",
        rate:"80",
        des:"anda! anda! anda!",
        tag1:"bread",
        tag2:"butter"
    },
    {
        id: 44,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"hot-garlic-soup.jpg",
        category:"non-veg",
        type:"soup",
        name:"hot garlic",
        rate:"160",
        des:"superb soup",
        tag1:"paper",
        tag2:"hot_sause"
    },
    {
        id: 45,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"pumpkin-soup.jpg",
        category:"non-veg",
        type:"soup",
        name:"halo rice",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"lite",
        tag2:"hot"
    },
    {
        id: 46,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"indian-thali.jpg",
        category:"non-veg",
        type:"meal",
        name:"indian thali",
        rate:"850",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },
    {
        id: 47,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"isabella.jpg",
        category:"veg",
        type:"drink",
        name:"isabella",
        rate:"140",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 48,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"jalebi.jpg",
        category:"veg",
        type:"dessert",
        name:"jalebi",
        rate:"80",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 49,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"kashmiri-kewa.jpg",
        category:"veg",
        type:"drink",
        name:"kashmiri kewa",
        rate:"120",
        des:"jaffrani hot drinks with almond",
        tag1:"signature👌",
        tag2:"haven"
    },
    {
        id: 50,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"kashmiri-tuch.jpg",
        category:"non-veg",
        type:"starter",
        name:"kashmiri tucch",
        rate:"250",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 51,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"karwari-prawn.jpg",
        category:"non-veg",
        type:"meal",
        name:"karwari prawn",
        rate:"300",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 99,
        fnc: function print(arg){ return(arg)},
        offer:"15",
        img:"veg-polao.jpg",
        category:"veg",
        type:"meal",
        name:"kashmiri polao",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 52,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"choco-lava.jpg",
        category:"",
        type:"dessert",
        name:"lava stock",
        rate:"100",
        des:" chocolate ganache in core",
        tag1:"chocolate",
        tag2:"icecream"
    },
    {
        id: 53,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"laddu.jpg",
        category:"veg",
        type:"dessert",
        name:"laddu",
        rate:"40",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 54,
        fnc: function print(arg){ return(arg)},
        offer:"15",
        img:"lamb-stake.jpg",
        category:"non-veg",
        type:"starter",
        name:"lamb stake",
        rate:"300",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 55,
        fnc: function print(arg){ return(arg)},
        offer:"20",
        img:"lisa-fotios.jpg",
        category:"veg",
        type:"drink",
        name:"lisa fotios",
        rate:"300",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 57,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"manchurian.jpg",
        category:"non-veg",
        type:"meal",
        name:"manchurian",
        rate:"115",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },{
        id: 58,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"max-griss.jpg",
        category:"veg",
        type:"dessert",
        name:"max griss",
        rate:"175",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 59,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"mughlai-mutton.jpg",
        category:"non-veg",
        type:"meal",
        name:"mughlai mutton",
        rate:"400",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 60,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"murg-de-roti.jpg",
        category:"non-veg",
        type:"meal",
        name:"murg de tandur",
        rate:"180",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 61,
        fnc: function print(arg){ return(arg)},
        offer:"10",
        img:"mutton-biriyani.jpg",
        category:"non-veg",
        type:"meal",
        name:"mutton biriyani",
        rate:"400",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },
    {
        id: 105,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"maggi.jpg",
        category:"",
        type:"lite",
        name:"maggi",
        rate:"65",
        des:"I don't know what to write here 😏",
        tag1:"lite",
        tag2:"veg"
    },
    {
        id: 62,
        fnc: function print(arg){ return(arg)},
        offer:"15",
        img:"margareta-pizza.jpg",
        category:"",
        type:"pizza",
        name:"margareta pizza",
        rate:"500",
        des:"I don't know what to write here 😏",
        tag1:"Italy",
        tag2:"cheese"
    },
    {
        id: 63,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"mix-veg-soup.jpg",
        category:"",
        type:"soup",
        name:"mix veg",
        rate:"100",
        des:"lite and lovable",
        tag1:"carrot",
        tag2:"beans"
    },
    {
        id: 64,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"north-pool.jpg",
        category:"veg",
        type:"drink",
        name:"north pool",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 65,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"oleg-magni.jpg",
        category:"veg",
        type:"drink",
        name:"oleg magni",
        rate:"145",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },{
        id: 66,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"oreo-shake.jpg",
        category:"veg",
        type:"drink",
        name:"oreo ritaE",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 67,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"orange-smothee.jpg",
        category:"veg",
        type:"lite",
        name:"orange moose",
        rate:"150",
        des:"orange delight",
        tag1:"season",
        tag2:"sweet"
    },
    {
        id: 68,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"paneer-masala.jpg",
        category:"veg",
        type:"meal",
        name:"paneer mashala",
        rate:"190",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },{
        id: 69,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"paneer-tikka.jpg",
        category:"veg",
        type:"starter",
        name:"paneer tikka",
        rate:"130",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 70,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"pasta.jpg",
        category:"non-veg",
        type:"meal",
        name:"pasta",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 71,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"punjabi-thali.jpg",
        category:"non-veg",
        type:"meal",
        name:"punjabi thali",
        rate:"300",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 72,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"papicana-soup.jpg",
        category:"veg",
        type:"soup",
        name:"papicana",
        rate:"170",
        des:"I don't know what to write here 😏",
        tag1:"paper",
        tag2:"chili"
    },
    {
        id: 73,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"bay-pizza.jpg",
        category:"veg",
        type:"pizza",
        name:"Pizza bayGarlic",
        rate:"400",
        des:"enjoy with coldrinks",
        tag1:"Cheese",
        tag2:"handtoast"
    },
    {
        id: 74,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"chicken-origano.jpg",
        category:"",
        type:"pizza",
        name:"Pugliese Pizza",
        rate:"400",
        des:"rosemery, thyme and origano.",
        tag1:"signature👌",
        tag2:"mozarella",
    },
    {
        id: 75,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"pinaple-pancake.jpg",
        category:"",
        type:"dessert",
        name:"pinaple pancake",
        rate:"70",
        des:"honey and pinaple",
        tag1:"jelly",
        tag2:"butter"
    },{
        id: 76,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"fugazetta.jpg",
        category:"",
        type:"pizza",
        name:"pizza fugazetta",
        rate:"700",
        des:"I don't know what to write here 😏",
        tag1:"colombia",
        tag2:"olive"
    },
    {
        id: 77,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"raw-puli.jpg",
        category:"veg",
        type:"dessert",
        name:"puli pitha",
        rate:"250",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },
    {
        id: 56,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"luchi.jpg",
        category:"veg",
        type:"meal",
        name:"radhabalhavi",
        rate:"20",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 78,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"rose-pattle.jpg",
        category:"non-veg",
        type:"dessert",
        name:"rose pattle",
        rate:"130",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 79,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"rogan-josh.jpg",
        category:"non-veg",
        type:"meal",
        name:"rogan josh",
        rate:"400",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },{
        id: 80,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"rosogolla.jpg",
        category:"veg",
        type:"dessert",
        name:"rosogolla",
        rate:"25",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 81,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"sahi-paneer.jpg",
        category:"veg",
        type:"meal",
        name:"sezwan paneer",
        rate:"250",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 82,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"samosa.jpg",
        category:"veg",
        type:"starter",
        name:"samosa",
        rate:"40",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 83,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"sashmi-chicken.jpg",
        category:"non-veg",
        type:"starter",
        name:"sashmi chicken",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 84,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"shahi-chicken.jpg",
        category:"non-veg",
        type:"meal",
        name:"sahi chicken",
        rate:"250",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 85,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"sheri-silver-ice.jpg",
        category:"non-veg",
        type:"dessert",
        name:"sheri silver",
        rate:"210",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },{
        id: 86,
        fnc: function print(arg){ return(arg)},
        offer:"5",
        img:"sikh-kabab.jpg",
        category:"non-veg",
        type:"starter",
        name:"sikh kabab",
        rate:"200",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 87,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"steam-momo.jpg",
        category:"non-veg",
        type:"starter",
        name:"steam momo",
        rate:"150",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 88,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"strawberry-pie.jpg",
        category:"non-veg",
        type:"dessert",
        name:"strawberry pie",
        rate:"170",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 89,
        fnc: function print(arg){ return(arg)},
        offer:"10",
        img:"strawberry-splash.jpg",
        category:"veg",
        type:"drink",
        name:"strawberry z",
        rate:"220",
        des:"I don't know what to write here 😏",
        tag1:"signature👌",
        tag2:"tag2",
    },
    {
        id: 90,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"cheese-burst-olive.jpg",
        category:"non-veg",
        type:"pizza",
        name:"St. Louis Style",
        rate:"500",
        des:"extra cheese with olive",
        tag1:"southAmerican",
        tag2:"basil"
    },
    {
        id: 91,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"salmon-rost.jpg",
        category:"non-veg",
        type:"starter",
        name:"salmon rost",
        rate:"120",
        des:"roasted salmon curry",
        tag1:"lemon",
        tag2:"bengali"
    },
    {
        id: 92,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"shawarma-wrap.jpg",
        category:"non-veg",
        type:"meal",
        name:"shawarma wrap",
        rate:"120",
        des:"smoked shawarma with meo",
        tag1:"chicken",
        tag2:"meo_mint"
    },
    {
        id: 107,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"sondesh.jpg",
        category:"veg",
        type:"dessert",
        name:"sondesh",
        rate:"200",
        des:"Box full of sweet",
        tag1:"signature👌",
        tag2:"ligt"
    },
    {
        id: 93,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"tomato-soup.jpg",
        category:"veg",
        type:"soup",
        name:"tomato soup",
        rate:"80",
        des:"I don't know what to write here 😏",
        tag1:"tangi",
        tag2:"lite"
    },
    {
        id: 94,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"tanduri-chicken.jpg",
        category:"non-veg",
        type:"starter",
        name:"tandoori chicken",
        rate:"700",
        des:"barbeque whole chicken",
        tag1:"test",
        tag2:"topSeller"
    },
    {
        id: 95,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"tanduri-chole.jpg",
        category:"non-veg",
        type:"meal",
        name:"tanduri chole",
        rate:"170",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 96,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"vanila-splash.jpg",
        category:"veg",
        type:"dessert",
        name:"vanilla splash",
        rate:"110",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 97,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"veg-biriyani.jpg",
        category:"veg",
        type:"meal",
        name:"veg biriyani",
        rate:"180",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 98,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"veg-pakora.jpg",
        category:"veg",
        type:"starter",
        name:"veg pakora",
        rate:"120",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },{
        id: 100,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"veg-saate.jpg",
        category:"veg",
        type:"starter",
        name:"veg saate",
        rate:"160",
        des:"I don't know what to write here 😏",
        tag1:"tag1",
        tag2:"tag2",
    },
    {
        id: 101,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"veg-thali.jpg",
        category:"veg",
        type:"meal",
        name:"veg thali",
        rate:"300",
        des:"I don't know what to write here 😏",
        tag1:"sabzi",
        tag2:"rice",
    },
    {
        id: 102,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"waffle-vanilla-love.jpg",
        category:"non-veg",
        type:"dessert",
        name:"vanilla love",
        rate:"110",
        des:"chocochips inside",
        tag1:"waffle",
        tag2:"iceceam"
    },
    {
        id: 103,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"old-wine.jpg",
        category:"drink",
        type:"drink",
        name:"wine",
        rate:"600",
        des:"premium and perfect",
        tag1:"signature👌",
        tag2:"booze"
    },
    {
        id: 106,
        fnc: function print(arg){ return(arg)},
        offer:"0",
        img:"zafrani-biriyani.jpg",
        category:"non-veg",
        type:"meal",
        name:"zafrani biriyani",
        rate:"400",
        des:"Arabic style biriyani.",
        tag1:"signature👌",
        tag2:"best_seller"
    }
]

export {Food}